version: 3.3.1.2

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore
  
build:
  project: FluentBootstrap.sln
  
artifacts:
  - path: FluentBootstrap\bin\Release\FluentBootstrap.dll
    name: FluentBootstrap.dll
  - path: '**\FluentBootstrap.*.nupkg'
